# doublon avec indexcontroller
#home:
#    path: /
#    controller: App\Controller\ShiniGamiController::index

security.validate:
    path: /connexion/signIn/validate
    controller: App\Controller\SecurityController::validation
