# doublon avec indexcontroller
#home:
#    path: /
#    controller: App\Controller\ShiniGamiController::index

secure.validate:
    path: /connect/validate
    controller: App\Controller\SecurityController::validation
