<?php
/**
 * Created by PhpStorm.
 * User: Etudiant
 * Date: 23/01/2019
 * Time: 11:52
 */

namespace App\Service\ImageSaver;


use Symfony\Component\Asset\Packages;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class ImageSaverType
 *
 * An image uploader that store image for you.
 * Image will be move under Symfony 'public' folder at 'myImages/' by default,
 * or whatever folder name you specified in your entity private '$folder' attribute..
 *
 * The field is 'dropified' by default, but you can revert to basic one...
 *
 * @package App\Service\ImageSaver
 */
class ImageSaverType extends AbstractType
{
    /**
    * @var Packages
    */
    private $package;

    /**
     * ImageSaverType constructor.
     * @param $package
     */
    public function __construct(Packages $package)
    {
        $this->package = $package;
    }


    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('image', FileType::class, [
                'label' => false,
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'class' => 'dropify',
                    'data-default-file' => $options['data-default-file']()
                ]
            ])
            ->addEventSubscriber(new ImageSaver($this->package, $this))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'mapped' => false,
            'data-default-file' => function(){
                dump($this);
                return 'data-resolver';
            }
/*            'data-default-file' => function(){
                dump($this);
                die();
            }*/
        ]);
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
        // Todo: Modifier dans la vue l'image url
    }
}